api:
  gateway:
    client:
      details:
        request:
          api:
            key: ${API_GATEWAY_REQUEST_APIKEY:dummy-key}
          base:
            url: ${API_GATEWAY_REQUEST_BASE_URL:dummy-url}
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher