api:
  gateway:
    client:
      details:
        request:
          api:
            key: ${API_GATEWAY_REQUEST_APIKEY:dummy-key}
          base:
            url: ${API_GATEWAY_REQUEST_BASE_URL:dummy-url}
info:
  app:
    description: This is Template App.
    name: LOS Template App
    version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  management:
    endpoint:
      health:
        group:
          custom:
            show-components: always
            show-details: always